version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: grades-sql
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ng_Passw0rd!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./db:/var/opt/mssql/backup
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-C", "-S", "localhost,1433", "-U", "sa", "-P", "Str0ng_Passw0rd!", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: src/Grades.Api/Dockerfile
    container_name: grades-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__GradesDb: "Server=sqlserver,1433;Database=GradesDB;User ID=sa;Password=Str0ng_Passw0rd!;Encrypt=true;TrustServerCertificate=true"
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  mssql-data:
